name: First Homework

on: push

jobs:
  my-job:
    name: First Homework
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to foo-bar.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'bot-webdev.surge.sh'
          project: '.'
          login: ${{ secrets.SURGE_USERNAME }}
          token: ${{ secrets.SURGE_TOKEN }}
